// Translations of existing labels, not additional biographical claims.
export const polishLabels = {
  'Main navigation': 'Nawigacja główna', 'Language': 'Język', 'Introduction': 'Wprowadzenie',
  'Michal Maciej Mazur home': 'Michał Maciej Mazur: strona główna',
  'Years in Japan': 'Lata w Japonii', 'Primary links': 'Najważniejsze odnośniki',
  'Personal trajectory': 'Droga zawodowa',
  "Key moments in Michal Mazur's path in Japan": 'Wybrane etapy drogi Michała Mazura w Japonii',
  'Selected moments from my work and life in Japan': 'Wybrane chwile z mojej pracy i życia w Japonii',
  'Professional biography': 'Biografia zawodowa', 'My current academic home at APU': 'Moja obecna uczelnia: APU',
  'Selected practice': 'Wybrane projekty', 'Workshop portfolio': 'Oferta warsztatów',
  'Workshop design outputs': 'Materiały wypracowane podczas warsztatów', 'Selected evidence': 'Dokumentacja projektów',
  'Positioning statement': 'Obszary mojej pracy', 'Editorial reporting evidence': 'Dokumentacja pracy reporterskiej',
  'Signature essay': 'Esej programowy', 'Contact options': 'Możliwości kontaktu',
  'Original workshop material': 'Oryginalne materiały warsztatowe',
  'Workshop photographs': 'Zdjęcia z warsztatów', 'Previous workshop photograph': 'Poprzednie zdjęcie z warsztatów', 'Next workshop photograph': 'Następne zdjęcie z warsztatów',
  'Teaching portfolio sections': 'Sekcje portfolio dydaktycznego', 'Research portfolio sections': 'Sekcje portfolio badawczego', 'Writing portfolio sections': 'Sekcje portfolio pisarskiego', 'Public record sections': 'Sekcje dorobku',
  'Understanding Video Games course posters': 'Plakaty kursu Understanding Video Games', 'Original Understanding Video Games posters': 'Oryginalne plakaty Understanding Video Games',
  'Teaching materials in practice': 'Materiały dydaktyczne w praktyce', 'Teaching problem': 'Problem dydaktyczny', 'Selected videos': 'Wybrane nagrania',
  'Watch Contemporary Japanese Education System conversation on YouTube': 'Obejrzyj rozmowę Contemporary Japanese Education System na YouTube',
  'Watch Intercultural Communication for Living in a Global Society on YouTube': 'Obejrzyj Intercultural Communication for Living in a Global Society na YouTube',
  'Watch Understanding Video Games on YouTube': 'Obejrzyj Understanding Video Games na YouTube',
  'Watch interview about academic life in Hokkaido and PSX Extreme on YouTube': 'Obejrzyj wywiad o pracy akademickiej na Hokkaido i PSX Extreme na YouTube',
};
export const polishAlts = {
  'An editorial workspace blending academic books, Japanese urban light, and subtle media culture references.': 'Biurko z książkami akademickimi, światłami japońskiego miasta i odniesieniami do kultury mediów.',
  'Michal Maciej Mazur outdoors in Japan, smiling in front of a mountain landscape.': 'Uśmiechnięty Michał Maciej Mazur na tle górskiego krajobrazu w Japonii.',
  'Michal Mazur facilitating a hybrid intercultural communication workshop at Hokkaido University.': 'Michał Mazur prowadzi hybrydowe warsztaty komunikacji międzykulturowej na Hokkaido University.',
  'Michal Mazur speaking into a podcast microphone in a Nintendo Tokyo shirt.': 'Michał Mazur w koszulce Nintendo Tokyo nagrywa podcast.',
  'Michal Mazur standing beside a distinctive traditional Japanese mailbox figure.': 'Michał Mazur przy charakterystycznej japońskiej skrzynce pocztowej.',
  'Michal Mazur standing in the entrance of Ritsumeikan Asia Pacific University in Beppu.': 'Michał Mazur przy wejściu do Ritsumeikan Asia Pacific University w Beppu.',
  'Ritsumeikan Asia Pacific University campus in Beppu, framed by cherry blossom trees.': 'Kampus Ritsumeikan Asia Pacific University w Beppu w otoczeniu kwitnących wiśni.',
  'A university workshop room used as a soft background.': 'Sala warsztatowa na uczelni w rozmytym tle.',
  'Michal Mazur with game director Toshihiro Nagoshi during an interview.': 'Michał Mazur z twórcą gier Toshihiro Nagoshim podczas wywiadu.',
  'Michal Mazur with the creators of Valkyrie Profile during an interview visit.': 'Michał Mazur z twórcami Valkyrie Profile podczas wywiadu.',
  'Original APU Pre-FD Workshop Series poster.': 'Oryginalny plakat serii warsztatów APU Pre-FD.',
  'Michal Mazur in discussion with workshop participants.': 'Michał Mazur rozmawia z uczestnikami warsztatów.',
  'Michal Mazur leading a presentation-skills workshop with university participants.': 'Michał Mazur prowadzi warsztaty umiejętności prezentacyjnych na uczelni.',
  'Michal Mazur with an international student group after a Student Success workshop.': 'Michał Mazur z międzynarodową grupą studentów po warsztatach Student Success.',
  'Michal Mazur facilitating a Teaching in English workshop with university staff.': 'Michał Mazur prowadzi warsztaty Teaching in English dla pracowników uczelni.',
  'Michal Mazur inviting questions during a Teaching in English workshop at Hokkaido University in 2019.': 'Michał Mazur zaprasza do zadawania pytań podczas warsztatów Teaching in English na Hokkaido University w 2019 roku.',
  'Michal Mazur leading a Teaching in English workshop on intercultural body language at Hokkaido University in 2019.': 'Michał Mazur prowadzi warsztaty Teaching in English o międzykulturowej mowie ciała na Hokkaido University w 2019 roku.',
  'Michal Mazur at a faculty-development lecture on applications of generative AI in education and research.': 'Michał Mazur podczas wykładu dla kadry o zastosowaniach generatywnej AI w edukacji i badaniach.',
  'Michal Mazur with an international university class after a teaching session.': 'Michał Mazur z międzynarodową grupą studentów po zajęciach.',
  'Original Michal Mazur slide showing a presentation as a four-part story: setup, problem, solution, and conclusion.': 'Slajd Michała Mazura przedstawiający prezentację jako opowieść w czterech częściach: wprowadzenie, problem, rozwiązanie i zakończenie.',
  'Original Michal Mazur slide showing five elements of activity design: purpose, task, time, grouping, and product.': 'Slajd Michała Mazura z pięcioma elementami projektowania aktywności: cel, zadanie, czas, podział na grupy i rezultat.',
  'Original Michal Mazur slide about mindful listening in the classroom, with attentive listening and culturally sensitive paraphrasing.': 'Slajd Michała Mazura o uważnym słuchaniu na zajęciach i parafrazowaniu z uwzględnieniem różnic kulturowych.',
  'Original Michal Mazur slide with a Japanese decision flow for using generative AI safely.': 'Slajd Michała Mazura ze schematem podejmowania decyzji o bezpiecznym użyciu generatywnej AI, po japońsku.',
  'Michal Mazur working with a small group during a Presentation Skills workshop at Hokkaido University.': 'Michał Mazur pracuje z małą grupą podczas warsztatów Presentation Skills na Hokkaido University.',
  'Michal Mazur preparing a camera and classroom technology for teaching.': 'Michał Mazur przygotowuje kamerę i sprzęt do prowadzenia zajęć.',
  'Michal Mazur with an international student group in a university classroom.': 'Michał Mazur z międzynarodową grupą studentów w sali zajęciowej.',
  'Michal Mazur speaking during a recorded conversation about games, Japan, and academic life.': 'Michał Mazur podczas nagrania rozmowy o grach, Japonii i pracy akademickiej.',
  'Students featured in the Intercultural Communication course video.': 'Studenci występujący w nagraniu kursu Intercultural Communication.',
  'Michal Mazur in an interview about academic life and PSX Extreme.': 'Michał Mazur w wywiadzie o pracy akademickiej i PSX Extreme.',
  'Original AP House Dialogue Cafe poster for Starting Over.': 'Oryginalny plakat Starting Over w ramach AP House Dialogue Cafe.',
  'Original University of Tokyo PAGE guest workshops poster.': 'Oryginalny plakat gościnnych warsztatów PAGE na University of Tokyo.',
  'Original International Project Management Program participant cover.': 'Oryginalna okładka materiałów dla uczestników International Project Management Program.',
};
